services:
  shortliner:
    build:
      context: .
      dockerfile: Dockerfile
    image: shortliner
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - shortliner-net

networks:
  shortliner-net:
    external: true