-- Schema as previously generated by Hibernate (ddl-auto=update). Existing databases are
-- baselined at version 1 (spring.flyway.baseline-on-migrate), so this only runs on empty ones.
CREATE TABLE url_entity (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    short_code VARCHAR(255),
    updated_at TIMESTAMP(6),
    url        VARCHAR(255),
    CONSTRAINT url_entity_pkey PRIMARY KEY (id),
    CONSTRAINT uk_url_entity_short_code UNIQUE (short_code)
);
